[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_twitter = "HWmi9B99PCoGST8JRvhyrErGC3PYzXiiA21EWS4q99Cw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/ana/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
